declare interface IWorldClockSliderWebPartStrings {
  UseCorsFieldDescription:string; 
  ConvertFromUTCFieldDescription:string; 
  ConvertFromUTCOptionNo:string; 
  ConvertFromUTCOptionYes:string; 
  ConvertFromUTCLabel:string; 
  MaxTotalFieldDescription:string; 
  MaxTotalFieldLabel:string; 
  FilmStripAriaLabel:string; 
  PropertyPaneDescription: string;
  BasicGroupName: string;
  AllItemsUrlFieldLabel:string; 
  FeedUrlFieldLabel:string; 
  FeedTypeFieldLabel:string; 
  PlaceholderTitle:string; 
  PlaceholderDescription:string;
  ConfigureButton:string; 
  FeedTypeOptionGoogle:string; 
  FeedTypeOptionCal:string; 
  FeedTypeOptionRSS:string;
  FeedTypeOptionWordPress:string; 
  FeedUrlCallout:string; 
  MaxEventsFieldLabel:string; 
  MaxEventsFieldDescription:string; 
  DateRangeFieldLabel:string;
  DateRangeOptionWeek:string; 
  DateRangeOptionUpcoming:string; 
  DateRangeOptionTwoWeeks:string; 
  DateRangeOptionMonth:string; 
  DateRangeOptionQuarter:string; 
  UseCORSFieldCallout:string; 
  UseCORSFieldCalloutDisabled:string; 
  CORSOn:string; 
  CORSOff:string; 
  AdvancedGroupName:string; 
  FocusZoneAriaLabelReadMode:string; 
  FocusZoneAriaLabelEditMode:string; 
  EventCardWrapperArialLabel:string; 
  Loading:string; 
  NoEventsMessage:string; 
  CacheDurationFieldLabel:string; 
  CacheDurationFieldCallout:string; 
  FeedUrlValidationNoUrl:string; 
  FeedUrlValidationInvalidFormat:string; 
  ErrorMessage:string; 
  NextButtonLabel:string; 
  PrevButtonLabel:string; 
  NextButtonAriaLabel:string; 
  PrevButtonAriaLabel:string; 
  ErrorNotFound:string; 
  ErrorMixedContent:string; 
  ErrorFailedToFetch:string; 
  ErrorFailedToFetchNoProxy:string; 
  ErrorRssNoResult:string; 
  ErrorRssNoRoot:string; 
  ErrorRssNoChannel:string; 
  ErrorInvalidCalFeed:string; 
  ErrorInvalidWordPressFeed:string; 
  AddToCalendarAriaLabel:string; 
  AddToCalendarButtonLabel:string; 
  AllDayDateFormat:string; 
  LocalizedTimeFormat:string; 
  FeedSettingsGroupName:string;
  DescriptionFieldLabel:string;
    DescriptionFieldLabel: string;
}

declare module 'WorldClockSliderWebPartStrings' {
  const strings: IWorldClockSliderWebPartStrings;
  export = strings;
}
